//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SirfDealsMvc4
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public string ImageId { get; set; }
        public string ImageUrl { get; set; }
        public Nullable<decimal> Price { get; set; }
        public string CouponCode { get; set; }
        public string AffiliateLink { get; set; }
        public Nullable<System.DateTime> ExpiryDate { get; set; }
        public Nullable<int> CategoryId { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<System.DateTime> PostedDate { get; set; }
        public string Website { get; set; }
        public Nullable<int> Clicks { get; set; }
        public Nullable<int> PercentageOff { get; set; }
    }
}
